# Generated by Django 5.1 on 2026-01-31 20:54

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('admin_name', models.CharField(max_length=255)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admin Session',
                'verbose_name_plural': 'Admin Sessions',
                'db_table': 'admin_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.TextField()),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('bio', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('rubrics', 'Rubrics'), ('medicines', 'Medicines'), ('grades', 'Grade Mappings'), ('synonyms', 'Synonyms')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('records_total', models.IntegerField()),
                ('records_added', models.IntegerField()),
                ('records_failed', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import History',
                'verbose_name_plural': 'Import Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('latin_name', models.CharField(max_length=200)),
                ('name_hindi', models.CharField(blank=True, max_length=200)),
                ('common_name', models.CharField(blank=True, max_length=200)),
                ('family', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_hindi', models.TextField(blank=True)),
                ('available_potencies', models.CharField(max_length=200)),
                ('usage_count', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='homeopathy__name_ad9da2_idx'), models.Index(fields=['latin_name'], name='homeopathy__latin_n_c2781b_idx'), models.Index(fields=['is_active'], name='homeopathy__is_acti_67d284_idx'), models.Index(fields=['-usage_count'], name='homeopathy__usage_c_c4ae8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('medical_history', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='homeopathy.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('chief_complaint', models.TextField()),
                ('symptoms', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10)),
                ('patient_phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('follow_up', 'Follow-up'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('prescribed_potency', models.CharField(blank=True, max_length=20)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='homeopathy.doctor')),
                ('prescribed_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_cases', to='homeopathy.medicine')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='homeopathy.patient')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repertorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='weighted_sum', max_length=50)),
                ('total_rubrics', models.IntegerField()),
                ('total_medicines_analyzed', models.IntegerField()),
                ('pdf_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertorizations', to='homeopathy.case')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertorizations', to='homeopathy.doctor')),
            ],
            options={
                'verbose_name': 'Repertorization',
                'verbose_name_plural': 'Repertorizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepertorizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rubrics_covered', models.IntegerField()),
                ('grade_1_count', models.IntegerField(default=0)),
                ('grade_2_count', models.IntegerField(default=0)),
                ('grade_3_count', models.IntegerField(default=0)),
                ('grade_4_count', models.IntegerField(default=0)),
                ('grade_5_count', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeopathy.medicine')),
                ('repertorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='homeopathy.repertorization')),
            ],
            options={
                'verbose_name': 'Repertorization Result',
                'verbose_name_plural': 'Repertorization Results',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('name_hindi', models.CharField(blank=True, max_length=500)),
                ('level', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('description_hindi', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='homeopathy.rubric')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
                'ordering': ['level', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField()),
                ('top_medicine_1_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('top_medicine_2_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('top_medicine_3_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('pdf_report', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='homeopathy.patient')),
                ('top_medicine_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homeopathy.medicine')),
                ('top_medicine_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homeopathy.medicine')),
                ('top_medicine_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='homeopathy.medicine')),
                ('matched_rubrics', models.ManyToManyField(related_name='patient_searches', to='homeopathy.rubric')),
            ],
            options={
                'verbose_name': 'Patient Search',
                'verbose_name_plural': 'Patient Searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_type', models.CharField(choices=[('aggravation', 'Aggravation'), ('amelioration', 'Amelioration')], max_length=15)),
                ('name', models.CharField(max_length=500)),
                ('name_hindi', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalities', to='homeopathy.rubric')),
            ],
            options={
                'verbose_name': 'Modality',
                'verbose_name_plural': 'Modalities',
                'ordering': ['modality_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=1)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_rubrics', to='homeopathy.case')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeopathy.rubric')),
            ],
            options={
                'verbose_name': 'Case Rubric',
                'verbose_name_plural': 'Case Rubrics',
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricMedicineGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 'Grade 1 - Mild'), (2, 'Grade 2 - Moderate'), (3, 'Grade 3 - Strong'), (4, 'Grade 4 - Very Strong'), (5, 'Grade 5 - Specific/Keynote')])),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_grades', to='homeopathy.medicine')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_grades', to='homeopathy.rubric')),
            ],
            options={
                'verbose_name': 'Rubric-Medicine Grade',
                'verbose_name_plural': 'Rubric-Medicine Grades',
                'ordering': ['-grade', 'medicine__name'],
            },
        ),
        migrations.CreateModel(
            name='RubricSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=500)),
                ('synonym_hindi', models.CharField(blank=True, max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='homeopathy.rubric')),
            ],
            options={
                'verbose_name': 'Rubric Synonym',
                'verbose_name_plural': 'Rubric Synonyms',
                'ordering': ['-is_primary', 'synonym'],
            },
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Full Database'), ('rubrics', 'Rubrics Only'), ('medicines', 'Medicines & Grades'), ('users', 'Users & Cases')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('backup_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='document')),
                ('records_count', models.IntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Backup',
                'verbose_name_plural': 'System Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='homeopathy__email_be1139_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='homeopathy__user_ty_d13d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='homeopathy__is_acti_0f4ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['registration_number'], name='homeopathy__registr_0d71b3_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active'], name='homeopathy__is_acti_cd77aa_idx'),
        ),
        migrations.AddIndex(
            model_name='importhistory',
            index=models.Index(fields=['-created_at'], name='homeopathy__created_b5456f_idx'),
        ),
        migrations.AddIndex(
            model_name='importhistory',
            index=models.Index(fields=['import_type'], name='homeopathy__import__75b158_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='homeopathy__is_acti_565218_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['assigned_doctor'], name='homeopathy__assigne_8a742d_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='homeopathy__case_nu_ae5e22_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['doctor', 'status'], name='homeopathy__doctor__fe53a6_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['patient'], name='homeopathy__patient_b8433b_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-created_at'], name='homeopathy__created_677e92_idx'),
        ),
        migrations.AddIndex(
            model_name='repertorization',
            index=models.Index(fields=['case'], name='homeopathy__case_id_2876ef_idx'),
        ),
        migrations.AddIndex(
            model_name='repertorization',
            index=models.Index(fields=['doctor'], name='homeopathy__doctor__1c8449_idx'),
        ),
        migrations.AddIndex(
            model_name='repertorization',
            index=models.Index(fields=['-created_at'], name='homeopathy__created_d3068b_idx'),
        ),
        migrations.AddIndex(
            model_name='repertorizationresult',
            index=models.Index(fields=['repertorization', 'rank'], name='homeopathy__reperto_c9d2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['name'], name='homeopathy__name_78c419_idx'),
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['parent', 'level'], name='homeopathy__parent__a4484d_idx'),
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['is_active'], name='homeopathy__is_acti_6f9621_idx'),
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['order'], name='homeopathy__order_7f79ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubric',
            unique_together={('name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='patientsearch',
            index=models.Index(fields=['patient', '-created_at'], name='homeopathy__patient_2cf86f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientsearch',
            index=models.Index(fields=['is_saved'], name='homeopathy__is_save_185c88_idx'),
        ),
        migrations.AddIndex(
            model_name='modality',
            index=models.Index(fields=['rubric', 'modality_type'], name='homeopathy__rubric__ecb4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='caserubric',
            index=models.Index(fields=['case'], name='homeopathy__case_id_663797_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricmedicinegrade',
            index=models.Index(fields=['rubric', 'medicine'], name='homeopathy__rubric__da2ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricmedicinegrade',
            index=models.Index(fields=['grade'], name='homeopathy__grade_d4acff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubricmedicinegrade',
            unique_together={('rubric', 'medicine')},
        ),
        migrations.AddIndex(
            model_name='rubricsynonym',
            index=models.Index(fields=['synonym'], name='homeopathy__synonym_c24bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricsynonym',
            index=models.Index(fields=['rubric'], name='homeopathy__rubric__be9795_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricsynonym',
            index=models.Index(fields=['is_primary'], name='homeopathy__is_prim_abfefe_idx'),
        ),
        migrations.AddIndex(
            model_name='systembackup',
            index=models.Index(fields=['-created_at'], name='homeopathy__created_4b9b86_idx'),
        ),
        migrations.AddIndex(
            model_name='systembackup',
            index=models.Index(fields=['backup_type'], name='homeopathy__backup__a5459c_idx'),
        ),
    ]
