# Generated by Django 5.1 on 2026-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeopathy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='available_potencies',
        ),
        migrations.AddField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(blank=True, default='', help_text='When this medicine should not be used'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='indications',
            field=models.TextField(blank=True, default='', help_text='Conditions this medicine is indicated for'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='potencies',
            field=models.CharField(blank=True, default='', help_text='Comma-separated potencies like 6C, 30C, 200C', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Source material (plant, mineral, animal, etc.)', max_length=255),
        ),
    ]
