# Generated by Django 5.1 on 2026-02-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeopathy', '0002_remove_medicine_available_potencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertorization',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repertorizations', to='homeopathy.case'),
        ),
    ]
