# Generated by Django 5.1 on 2026-02-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeopathy', '0003_alter_repertorization_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='aadhar_number',
            field=models.CharField(default='000000000000', help_text='12-digit Aadhar card number', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_class',
            field=models.CharField(choices=[('doctor_jp_nautiyal', 'Doctor JP Nautiyal'), ('core_team', 'Core Team'), ('individual', 'Individual')], default='individual', help_text='Classification of doctor', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(default='TEMP000000', help_text='Medical license number', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='pan_number',
            field=models.CharField(default='TEMP000000', help_text='10-character PAN card number', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['doctor_class'], name='homeopathy__doctor__2c3045_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['aadhar_number'], name='homeopathy__aadhar__875d17_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['pan_number'], name='homeopathy__pan_num_b14e32_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['license_number'], name='homeopathy__license_23ed76_idx'),
        ),
    ]
