# Generated by Django 5.1 on 2026-04-17 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeopathy', '0005_message_messageattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserubric',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_rubrics', to='homeopathy.importhistory'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='homeopathy.importhistory'),
        ),
        migrations.AddField(
            model_name='modality',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modalities', to='homeopathy.importhistory'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='homeopathy.importhistory'),
        ),
        migrations.AddField(
            model_name='rubricmedicinegrade',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_medicine_grades', to='homeopathy.importhistory'),
        ),
        migrations.AddField(
            model_name='rubricsynonym',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='homeopathy.importhistory'),
        ),
    ]
