# Generated by Django 5.1 on 2026-04-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeopathy', '0006_caserubric_source_import_importhistory_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='matched_rubrics',
            field=models.ManyToManyField(blank=True, related_name='messages', to='homeopathy.rubric'),
        ),
    ]
